[package]
name = "cpm8080_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpm8080_lib = {path = "../cpm8080_lib"}
log = {version = "0.4.17", default-features = false}
simple_logger = "*"